name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Site generation
        run: |
          # Move the placeholder page to the publication directory  
          mkdir site
          cp -r src/* site
      - name: Store PR id
        if: "github.event_name == 'pull_request'"
        run: echo ${{ github.event.number }} > ./site/pr-id.txt

      - name: Publishing directory for PR preview
        if: "github.event_name == 'pull_request'"
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./site
          retention-days: 3

      - name: Publication
        if: "github.ref_name == 'main' && (github.event_name == 'push' || github.event_name == 'schedule')"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site